#!/bin/bash

EXECUTABLE=gnl_exe
DIFF_FILE=diff_txt

echo -e "\033[32m[Test Makefile]\033[0m"
make -C libft/ fclean && make -C libft/ && gcc -Wall -Werror -Wextra -I libft/includes/ -c get_next_line.c
echo -e "\033[32m[Compilation du programme]\033[0m"
gcc -Wall -Werror -Wextra -I libft/includes/ -c main.c && gcc -o $EXECUTABLE get_next_line.o main.o -L libft/ -lft
echo -e "\033[32m[Lancement du programme]\n[Sauvegarde de l'execution dans \"diff.txt\"]\033[0m"
./$EXECUTABLE > $FILE

